# Generated by Django 4.1 on 2022-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
