# Generated by Django 4.1 on 2022-08-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_poll_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
