# Generated by Django 4.1 on 2022-08-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_duration_poll_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
