# Generated by Django 4.1 on 2022-08-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_option_count'),
        ('main_app', '0003_alter_poll_public'),
    ]

    operations = [
    ]
